###
### Local infrastructure for quick start ### 
###

version: "3"
services:
  mongodb:
    container_name: "mongodb"
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    volumes:
      - ./mongo_data:/data/db

